webAppUrl: "https://practice.expandtesting.com/notes/app/"
credentials:
  user: "danielnutu23@gmail.com"
  password: "jl+ogKOSBzxX87wGwWfVnyn53XHkUhLB"
  user2: "danielnutu55@yahoo.com"
  password2: "FR1QdS8hcM6tlY7wzA7D935oW5y8BUFi"
  user3: "danielnutu23+notes@gmail.com"
  password3: "jl+ogKOSBzxX87wGwWfVnyn53XHkUhLB"
  user4: "danielnutu23+profile@gmail.com"
  password4: "jl+ogKOSBzxX87wGwWfVnyn53XHkUhLB"